rsa:
  key:
    pubKeyFile: c:\tools\auth_key\id_key_rsa.pub
server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.190:3306/summer_operator?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: program
    password: IK@!n0U5h$3K$E
logging:
  level:
    com.qmmao.weiweischool: debug